### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by avill01** [bind-this/gshopper#43]
To-Do
- [ ] Change
- [ ] change availability to 'available'
- [ ] change purchasePrice to not decimal
- [ ] comment on order status to new line
- [ ] associations: remove Order.hasMany(Product), Product.belongsToMany(Order, through{Order_Product}) also vice-versa (Order belongs to many product), add User has many Reviews, add Product has many Reviews, add Category belongs to many Products
- [ ] Change product to findById, change 404 error throw.
- [ ] Set default scope in models to pull all associations
- [ ] SendStatus instead of .end(), also empty parentheses
- [ ] send product back instead of just a status code
- [ ]  but at least one category validation in product model
- [ ] Find All instead of FindOne in search-product route
- [ ] throw error instead of next(err) in orders api routes

Notes
- payment system should be third party
- think about infinite scroll 
- if live searching on database, use a debounce (lodash has a nice one)
- return search queries with order base on avg rating
- precompute average review with hook that runs on every new review

**Comment by alaq** [comment]
This has been carried over to [the wiki](https://github.com/bind-this/gshopper/wiki/Code-Reviews-%231-Notes).
